name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKERHUB_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Build the Docker image
      run: docker build . --file dockerfile --tag teocristescu/cicd06:latest
    - run: docker tag teocristescu/cicd07:latest teocristescu/cicd07:${GITHUB_SHA:0:7}
  
    - name: Docker Push
      run: docker push teocristescu/cicd07:${GITHUB_SHA:0:7}
